import { Code, ProofArticle, Section } from "@/components/ProofArticle";

export default function LocalizationPage(){return <ProofArticle dir="rtl" eyebrow="" title="عينة توطين عربية لتوثيق API" intro="الفكرة بسيطة: أسماء parameters تبقى كما هي، والشرح حولها يكون عربي واضح وقريب من طريقة كلام المطورين.">
 <Section title="كيف أتعامل مع المصطلحات"><p>ما أترجم كل كلمة. أبقي أسماء الكود والمصطلحات المعروفة مثل API وJSON وSDK كما هي، وأشرح معناها بالعربي عند الحاجة.</p><ul><li><code>location</code> و<code>gl</code> و<code>hl</code> و<code>async</code> تبقى كما هي.</li><li>النص العام يكون بالعربية الفصحى البسيطة.</li><li>أشرح السلوك بدل ما أخلق أسماء عربية جديدة للكود.</li></ul></Section>
 <Section title="location: اختياري"><p>يحدد الموقع الجغرافي الذي تريد محاكاة البحث منه. في هذا المشروع أستخدم مدينة محددة لكل سوق.</p><p>إذا كنت تحتاج أيضًا انحياز دولة واضح، استخدم <code>gl</code> مع <code>location</code>.</p><Code>{`location=Baghdad,Baghdad Governorate,Iraq\ngl=iq`}</Code></Section>
 <Section title="gl: انحياز الدولة"><p><code>gl</code> ليس موقع المستخدم. هو انحياز الدولة في Google، لذلك أشرحه منفصلًا عن <code>location</code>.</p></Section>
 <Section title="hl: لغة وlocale واجهة Google"><p><code>hl</code> لا يعني أن كل النتائج ستكون بلغة واحدة. هو يحدد لغة وlocale واجهة Google. يوجد <code>lr</code> إذا كان المطلوب تقييد لغة النتائج نفسها.</p><Code>{`ar-iq  // Iraq\nar-sa  // Saudi Arabia\nar-eg  // Egypt\nar-ma  // Morocco`}</Code></Section>
 <Section title="async: البحث غير المتزامن"><p>مع <code>async=true</code> يبدأ البحث أولًا، ثم يسترجع التطبيق النتيجة لاحقًا باستخدام Search ID وSearch Archive API.</p><p><code>async</code> و<code>no_cache</code> لا يُستخدمان معًا في نفس الطلب.</p></Section>
 <Section title="no_cache: التحكم بالـcache"><p>مع <code>no_cache=true</code> يطلب SerpApi نتيجة جديدة بدل نتيجة cached مطابقة. التوثيق الحالي يذكر أن النتائج المحفوظة للطلبات المتطابقة تنتهي تقريبًا بعد ساعة ولا تُحسب كبحث جديد من الحصة الشهرية.</p></Section>
 <Section title="output: صيغة النتيجة"><ul><li><code>json</code>: الصيغة الافتراضية.</li><li><code>html</code>: HTML الخام.</li><li><code>md</code>: Markdown لاستخدامات LLMs وAI agents.</li></ul></Section>
 <Section title="مثال سريع"><Code>{`import { getJson } from "serpapi";\n\nconst result = await getJson({\n  engine: "google",\n  api_key: process.env.SERPAPI_KEY!,\n  q: "أفضل أدوات الذكاء الاصطناعي للمبرمجين",\n  location: "Baghdad,Baghdad Governorate,Iraq",\n  gl: "iq",\n  hl: "ar-iq",\n});`}</Code></Section>
 <Section title="لو كانت هذه توثيقًا رسميًا"><p>سأراجع الكلمات مع مطورين من أكثر من بلد عربي، وأثبت المصطلحات التي يفهمونها فعلًا، ثم أستخدم نفس الكلمات في docs والفيديو والدعم.</p></Section>
 <Section title="المراجع الرسمية"><ul><li><a href="https://serpapi.com/search-api" target="_blank" rel="noreferrer">Google Search API documentation</a></li><li><a href="https://serpapi.com/google-countries" target="_blank" rel="noreferrer">Supported Google countries</a></li><li><a href="https://serpapi.com/google-languages" target="_blank" rel="noreferrer">Supported Google languages</a></li><li><a href="https://serpapi.com/locations" target="_blank" rel="noreferrer">SerpApi locations</a></li></ul></Section>
 </ProofArticle>}