import { Code, ProofArticle, Section } from "@/components/ProofArticle";

export default function LocalizationPage(){return <ProofArticle dir="rtl" eyebrow="عينة Localization مستقلة" title="كيف أُعرِّب توثيق API بدون تخريب لغة المطور" intro="عينة صغيرة مبنية على Google Search API: نحافظ على أسماء parameters والقيم كما هي، ونترجم السلوك والمعنى إلى عربية تقنية قابلة للمسح السريع.">
 <Section title="مبدأ العمل"><p>الهدف ليس ترجمة كل كلمة. المطور يجب أن يبقى قادرًا على الانتقال مباشرة من الشرح العربي إلى الكود الإنجليزي دون طبقة مصطلحات مصطنعة.</p><ul><li>أبقي <code>location</code> و<code>gl</code> و<code>hl</code> و<code>async</code> كما هي.</li><li>أستخدم العربية الفصحى للمحتوى المشترك إقليميًا.</li><li>أشرح API وJSON وcache وSDK بدل استبدالها بمصطلحات غير مألوفة.</li><li>أترجم السلوك، لا syntax.</li></ul></Section>
 <Section title="location — اختياري"><p>يحدد الموقع الجغرافي الذي تريد محاكاة انطلاق البحث منه. للحصول على سياق أقرب إلى مستخدم حقيقي، يُفضَّل تحديد الموقع على مستوى المدينة.</p><p>إذا استخدمت <code>location</code> وحده فقد تتأثر بعض النتائج أيضًا بدولة الـproxy؛ عندما تحتاج انحيازًا أوضح لدولة محددة، استخدم <code>gl</code> إلى جانبه.</p><Code>{`location=Baghdad,Baghdad Governorate,Iraq\ngl=iq`}</Code></Section>
 <Section title="gl — انحياز الدولة"><p>أشرح <code>gl</code> كـ«انحياز الدولة» بدل «موقع المستخدم». هذا يبقي الفرق واضحًا بين country bias وبين الموقع الجغرافي الذي يحاكيه <code>location</code>.</p></Section>
 <Section title="hl — لغة/locale واجهة Google"><p>لا أسمي <code>hl</code> ببساطة «لغة النتائج»، لأن ذلك قد يوحي بأنه يقيّد صفحات النتائج إلى لغة واحدة. <code>hl</code> يحدد language/locale المستخدم في Google، بينما يوجد <code>lr</code> عندما يريد المطور تقييد لغات النتائج.</p><Code>{`ar-iq  // Iraq\nar-sa  // Saudi Arabia\nar-eg  // Egypt\nar-ma  // Morocco`}</Code></Section>
 <Section title="async — البحث غير المتزامن"><p>عندما تكون <code>async=true</code> يرسل التطبيق البحث ثم يسترجع النتيجة لاحقًا بواسطة Search Archive API ومعرّف البحث. أبقي كلمة async واسم Search Archive API كما يعرفهما المطور، وأشرح السلوك بالعربية.</p><p>وأوضّح أيضًا أن <code>async</code> و<code>no_cache</code> لا يُستخدمان معًا في الطلب نفسه.</p></Section>
 <Section title="no_cache — التحكم بالـcache"><p>عندما تكون <code>no_cache=true</code> يجبر SerpApi على جلب نتيجة جديدة بدل استخدام نتيجة cached مطابقة. التوثيق الحالي يذكر أن cache للطلبات المتطابقة تنتهي تقريبًا بعد ساعة وأن النتائج cached لا تُحسب كبحث جديد من حصة الشهر. لا يُستخدم <code>no_cache</code> مع <code>async</code> في الطلب نفسه.</p></Section>\n <Section title="output — صيغة النتيجة"><ul><li><code>json</code>: بيانات منظمة، وهي القيمة الافتراضية.</li><li><code>html</code>: HTML الخام.</li><li><code>md</code>: Markdown مهيأ لاستخدامات LLMs وAI agents.</li></ul></Section>
 <Section title="Mini quick-start"><Code>{`import { getJson } from "serpapi";\n\nconst result = await getJson({\n  engine: "google",\n  api_key: process.env.SERPAPI_KEY!,\n  q: "أفضل أدوات الذكاء الاصطناعي للمبرمجين",\n  location: "Baghdad,Baghdad Governorate,Iraq",\n  gl: "iq",\n  hl: "ar-iq",\n});`}</Code></Section>
 <Section title="قرارات المصطلحات"><ul><li><strong>API:</strong> API، مع «واجهة برمجة التطبيقات» عند الحاجة لأول ذكر فقط.</li><li><strong>locale:</strong> أحتفظ بكلمة locale مع شرح عربي لأنها أدق من اختزالها إلى «لغة».</li><li><strong>cache:</strong> cache / التخزين المؤقت؛ أشرح السلوك مرة ولا أحمّل النص بمصطلح طويل كل مرة.</li><li><strong>server-side:</strong> server-side / على الخادم حتى تبقى حدود الأمان قابلة للربط مباشرة بكود Next.js.</li><li><strong>country bias:</strong> انحياز الدولة حتى لا يختلط مع الموقع الجغرافي.</li></ul></Section>
 <Section title="حدود العينة"><p>هذه ليست ترجمة رسمية من SerpApi. لو كانت localization إنتاجية، سأراجع المصطلحات مع مطورين عرب من أكثر من سوق، أستخدم support/search behavior لاكتشاف العبارات المربكة، وأحافظ على glossary موحدة بين docs والصفحات والفيديوهات والدعم.</p></Section>\n <Section title="المراجع الرسمية"><ul><li><a href="https://serpapi.com/search-api" target="_blank" rel="noreferrer">Google Search API documentation</a></li><li><a href="https://serpapi.com/google-countries" target="_blank" rel="noreferrer">Supported Google countries</a></li><li><a href="https://serpapi.com/google-languages" target="_blank" rel="noreferrer">Supported Google languages</a></li><li><a href="https://serpapi.com/locations" target="_blank" rel="noreferrer">SerpApi locations</a></li></ul></Section>
 </ProofArticle>}
