import { ProofArticle, Section } from "@/components/ProofArticle";

export default function FeedbackPage(){return <ProofArticle eyebrow="" title="Notes from building with SerpApi" intro="These are things I noticed while building the project. They come from my own use, so I would not treat them as broad customer research.">
 <Section title="The first request was easy"><p>The Playground made it quick to get a working request. Most of my questions came later, when I had to separate <code>location</code>, <code>gl</code>, and <code>hl</code>, deal with a slow search, and keep the API key out of the browser.</p></Section>
 <Section title="I would show location, gl, and hl together"><p>Each setting is documented, but a new developer can still read them as versions of the same thing. A small example that runs one query in two countries would make the difference easier to see.</p></Section>
 <Section title="I wanted a complete async TypeScript example"><p>When one search took about 33 seconds, I switched to async search and Search Archive. The building blocks are there, but I still had to decide retry timing, timeouts, final states, and what the UI should do when only some markets finish. A short TypeScript example covering the whole flow would have saved time.</p></Section>
 <Section title="A current Next.js server example would help"><p>The security guidance is clear that the API key should not be exposed in browser code. A small App Router example using a Route Handler, <code>process.env.SERPAPI_KEY</code>, and a client request to that route would make the safe pattern very easy to copy.</p></Section>
 <Section title="Finding the right local settings could be quicker"><p>I started from markets such as Iraq and Saudi Arabia, not from parameter names. A small market-to-parameter example near the localization docs could help people who think the same way.</p></Section>
 <Section title="Public demos have a quota problem"><p>A portfolio or tutorial can accidentally spend a live request every time somebody visits. A short note about caching or saved example results would be useful for people publishing demos on limited plans.</p></Section>
 <Section title="What worked well for me"><ul><li>The Playground made the first request quick to inspect.</li><li>The response included enough metadata to check which search context was used.</li><li>The JavaScript/TypeScript SDK fit cleanly into a Next.js server route.</li><li>Search IDs and Search Archive gave me a good way to handle slower searches.</li><li>The security docs are clear about keeping keys out of browser code.</li></ul></Section>
 </ProofArticle>}

