import { ProofArticle, Section } from "@/components/ProofArticle";

export default function FeedbackPage(){return <ProofArticle eyebrow="" title="Notes from using SerpApi" intro="These are notes from building this project as a new SerpApi user. They come from my own build, so I would check them against support data and other developers before treating them as product priorities.">
 <Section title="The short version"><p>The first request was easy to make in the Playground. The harder parts came later: understanding how <code>location</code>, <code>gl</code>, and <code>hl</code> differ, handling a slow search, and applying the API-key guidance in a current Next.js app.</p></Section>
 <Section title="1. Put location, gl, and hl in one example"><p>The three settings are documented separately, but a developer starting with a country or city can still mix them up. One example that runs the same query in two countries would make the difference easy to see.</p></Section>
 <Section title="2. Add a small TypeScript async example"><p>A Baghdad request took about 33 seconds. <code>async=true</code> and Search Archive solved the problem, but I still had to decide how often to check, when to stop, and what the UI should show while one city is still waiting. A short TypeScript polling example would save that setup time.</p></Section>
 <Section title="3. Show a current Next.js server example"><p>The security guidance is clear that API keys should not live in browser code. A small App Router example with a Route Handler, <code>process.env.SERPAPI_KEY</code>, and basic input validation would make the boundary obvious to frontend developers.</p></Section>
 <Section title="4. Make country and locale lookup easier to find"><p>Some developers start with a question like “How do I get results for Iraq?” instead of starting with a parameter name. A small country-to-parameter table or stronger cross-links from the Google Search API page could help.</p></Section>
 <Section title="5. Add a note for public demos"><p>A portfolio or hackathon demo can spend API quota every time someone visits. A short note about caching or saved results would help developers publish demos without surprises.</p></Section>
 <Section title="What went smoothly"><ul><li>The Playground made the first localized request easy to inspect.</li><li>The response metadata made it possible to check which settings were used.</li><li>The JavaScript/TypeScript SDK worked cleanly in a Next.js server route.</li><li>Search IDs and Search Archive gave me a workable path for slow requests.</li><li>The security docs are clear that the key should stay off the client.</li></ul></Section>
 <Section title="What I would check next"><p>I would compare these notes with support tickets, common developer questions, search timing data, and feedback from more users before recommending any docs or product change.</p></Section>
 </ProofArticle>}