import { ProofArticle, Section } from "@/components/ProofArticle";

export default function FeedbackPage(){return <ProofArticle eyebrow="First-hand product use" title="Product & documentation feedback" intro="Observations from building Arabic Search Context Lab as a new SerpApi user. These are deliberately separated from hypotheses that would need broader customer validation.">
 <Section title="Executive summary"><p>The first request was easy to discover through the Playground. Most friction appeared after that: understanding localization as three separate controls, designing around a slow search, and translating secure server-side guidance into a current Next.js application pattern.</p></Section>
 <Section title="1. Make the localization mental model easier to see together"><p><code>location</code>, <code>gl</code>, and <code>hl</code> are individually documented, but a market-oriented developer can still read them as overlapping variants. A short localized-search recipe showing the same query in two countries could make the distinction immediately visible.</p></Section>
 <Section title="2. Add an opinionated async TypeScript polling example"><p>A real Baghdad request took roughly 33 seconds. The documented async + Search Archive primitives solved the problem, but the developer still designs retry cadence, terminal states, timeout behavior, and partial UI states. A compact bounded-polling TypeScript helper would make this path easier.</p></Section>
 <Section title="3. Add a current Next.js server-side example"><p>SerpApi’s CORS/security guidance correctly keeps keys out of browser code. A current App Router example could connect that principle to a common stack: Route Handler, <code>process.env.SERPAPI_KEY</code>, input validation, and no secret in <code>NEXT_PUBLIC_*</code>.</p></Section>
 <Section title="4. Improve locale/location discoverability from a market-first starting point"><p>Developers sometimes begin with “I need Iraq/Saudi/Egypt/Morocco results,” not with the parameter name they need. Cross-linking location and locale discovery more prominently from localization parameters — or a tiny market-to-parameter example table — could shorten that path.</p></Section>
 <Section title="5. Public demo / quota guidance"><p>Tutorial and hackathon builders often want to publish demos without turning every visitor into a paid search. A short note on caching/snapshots/example results could help free-tier builders publish responsibly.</p></Section>
 <Section title="What worked well"><ul><li>Playground made the first localized request easy to inspect.</li><li>Structured metadata showed which context was actually used.</li><li>The JavaScript/TypeScript SDK fit naturally into a Next.js server runtime.</li><li>Search IDs + archive retrieval gave a clean option for slower searches.</li><li>Security guidance clearly discourages exposing keys in browser code.</li></ul></Section>
 <Section title="Validation boundary"><p>This is one developer’s build experience, not representative market research. Before treating any suggestion as a roadmap priority, I would compare it with support tickets, developer questions, search latency distribution, and feedback from regional advocates.</p></Section>
 </ProofArticle>}
