import { ProofArticle, Section } from "@/components/ProofArticle";

export default function PlanPage(){return <ProofArticle eyebrow="" title="What I would do in the first 90 days" intro="I would start by finding out where Arabic-speaking developers actually get stuck, ship a few useful resources, and keep the things people use.">
 <Section title="First month"><ul><li>Read support questions, onboarding issues, and the docs people already use.</li><li>Talk with Arabic-speaking developers in more than one market instead of treating the region as one audience.</li><li>Publish a small Arabic starting set: a quick start, a secure JavaScript/Next.js example, and a localization guide.</li><li>Use Baghdad as the easiest place for me to get in-person feedback, while keeping the wider plan regional.</li></ul></Section>
 <Section title="Second month"><ul><li>Write around problems developers are already trying to solve, not generic brand topics.</li><li>Run one small online technical session and pay attention to the questions people ask.</li><li>Work with a few existing developer communities before thinking about sponsorships or large events.</li><li>Turn at least one repeated question into a concrete docs, content, or product improvement.</li></ul></Section>
 <Section title="Third month"><ul><li>Keep the channels and topics that are producing real usage or useful conversations.</li><li>Drop the things that look busy but do not help developers get started.</li><li>Build one repeatable format, such as office hours, a workshop, or a small build challenge.</li><li>Write a short review of what worked, what did not, and what I would do next.</li></ul></Section>
 <Section title="Why I would start in Baghdad"><p>I live here, so I can talk to developers in person without pretending remote research is local knowledge. Iraqi Programmer Day is a useful place to listen and take notes. I would attend in my own capacity unless SerpApi explicitly asked me to represent the company.</p></Section>
 <Section title="What I would watch"><ul><li>How many people reach a first successful API request.</li><li>Which guides people finish or come back to.</li><li>What questions repeat across calls, events, and support.</li><li>Which feedback turns into a real docs, product, or content change.</li><li>Which community conversations turn into continued technical interest.</li></ul></Section>
 </ProofArticle>}
