import { ProofArticle, Section } from "@/components/ProofArticle";

export default function PlanPage(){return <ProofArticle eyebrow="" title="Arabic Developer Growth Plan: first 90 days" intro="A practical first-90-days plan based on the public information I could study before applying. I would change it once I had access to SerpApi's internal data and direct customer feedback.">
 <Section title="Main goal"><p>Help an Arabic-speaking developer get from “I need search data” to a successful first SerpApi request, then learn what makes them keep using it.</p></Section>
 <Section title="Days 1-30: learn where people get stuck"><ul><li>Read support and onboarding issues that already exist.</li><li>Separate the main Arabic-speaking developer groups by country, stack, and use case.</li><li>Publish a small Arabic starting set: quick-start, secure Next.js example, localization guide, and terminology notes.</li><li>Use Baghdad as the first place where I can talk to developers in person, while keeping the regional plan broader than Iraq.</li><li>Keep a simple list of repeated questions, what caused them, and what changed after a fix.</li></ul></Section>
 <Section title="Days 31-60: teach and test"><ul><li>Write around common developer tasks such as secure integrations, localized search, AI agents, monitoring, jobs, and local discovery.</li><li>Run one small online workshop and track attendance, first API calls, questions, and follow-up interest.</li><li>Get to know a few community organizers before asking them to promote anything.</li><li>Talk to companies or startups where search data clearly fits a current problem.</li><li>Turn at least one repeated developer problem into a docs, product, or content change.</li></ul></Section>
 <Section title="Days 61-90: keep what works"><ul><li>Compare markets and channels by activation, repeat interest, product fit, and effort.</li><li>Turn the strongest community relationship into something repeatable, such as office hours, a workshop series, or a small build challenge.</li><li>Build one complete campaign around the use case that got the best response.</li><li>Fill the content backlog from actual questions and product releases, not a generic SEO list.</li><li>Write a short 90-day review covering what worked, what did not, and what I would do next.</li></ul></Section>
 <Section title="Baghdad as the first in-person test"><p>Iraqi Programmer Day gives me a chance to talk with developers without travel. I would attend in my own name unless SerpApi explicitly asked me to represent the company. The point is to learn, not to pretend a partnership already exists.</p></Section>
 <Section title="What I would track"><ul><li>docs visits that lead to signup and a first successful request;</li><li>questions that keep coming up after tutorials or workshops;</li><li>developer and community conversations that lead to a real next step;</li><li>feedback that changes docs, product, or a campaign;</li><li>technical evaluations or partnership tests that continue past the first conversation.</li></ul></Section>
 </ProofArticle>}