import { ProofArticle, Section } from "@/components/ProofArticle";

export default function PlanPage(){return <ProofArticle eyebrow="Independent strategy exercise" title="Arabic Developer Growth Plan — first 90 days" intro="A learning-first plan for localized developer education, community trust, product feedback, and qualified adoption. It does not assume access to SerpApi’s internal data.">
 <Section title="North-star outcome"><p>Make it easier for an Arabic-speaking developer to move from “I need search data” → “I understand SerpApi” → “I make a successful first request” → “I can build with it confidently.” Measure activation and trust, not impressions alone.</p></Section>
 <Section title="Days 1–30 — listen, map, remove first friction"><ul><li>Review customer/support signals and onboarding errors.</li><li>Map Arabic developer segments and channels instead of treating the region as one audience.</li><li>Ship a small high-intent Arabic foundation: quick-start, secure JS/Next.js example, localization guide, terminology glossary.</li><li>Use Iraq as a field-learning wedge without making it the whole regional strategy.</li><li>Create a recurring Signal → Evidence → Suggested action → Outcome feedback loop.</li></ul></Section>
 <Section title="Days 31–60 — teach and run small experiments"><ul><li>Build content around developer jobs-to-be-done: secure integrations, localized search, AI agents, monitoring, jobs/local discovery.</li><li>Run one focused online workshop and measure questions, attendance, activation, and requested follow-ups.</li><li>Build two-way relationships with a small number of community operators before asking for distribution.</li><li>Pilot technical company/startup outreach around observable search-data needs.</li><li>Turn at least one repeated developer issue into a tangible docs/product/content improvement.</li></ul></Section>
 <Section title="Days 61–90 — scale signals that worked"><ul><li>Prioritize markets/channels by activation, repeat engagement, product fit, partner quality, and effort — not prestige.</li><li>Turn the strongest relationship into a repeatable program such as office hours, workshops, a small build challenge, or an open-source sprint.</li><li>Create one end-to-end localized campaign around a proven use case.</li><li>Source the backlog from real questions and product releases rather than generic SEO topics alone.</li><li>Publish a transparent 90-day review: tried, worked, failed, learned, stop, next.</li></ul></Section>
 <Section title="Iraq market wedge"><p>Baghdad gives direct physical access to an underrepresented Arabic developer ecosystem. Iraqi Programmer Day 2026 is a concrete near-term field-learning opportunity. Any attendance before employment would be in a personal capacity unless SerpApi explicitly authorized representation. The goal is developer discovery, not pretending a partnership already exists.</p></Section>
 <Section title="What I would measure"><ul><li>docs → signup → first successful request;</li><li>tutorial completion and recurring questions;</li><li>qualified developer/community conversations;</li><li>feedback that becomes a docs/product/campaign change;</li><li>qualified technical evaluations or partnership experiments.</li></ul></Section>
 </ProofArticle>}
