import { Code, ProofArticle, Section } from "@/components/ProofArticle";

export default function SourcePage(){
  return <ProofArticle eyebrow="Public source tour" title="How Arabic Search Context Lab is built" intro="A focused technical tour of the implementation. The standalone public repository is the canonical source; this page highlights the architecture and security decisions without exposing secrets.">
    <Section title="1. Market configuration is explicit"><p>The demo treats geography, country bias and Google locale as separate inputs. Each market has one canonical city-level location plus <code>gl</code> and <code>hl</code>.</p><Code>{`export const MARKETS = {\n  baghdad: {\n    location: "Baghdad,Baghdad Governorate,Iraq",\n    gl: "iq",\n    hl: "ar-iq",\n  },\n  riyadh: {\n    location: "Riyadh,Riyadh Province,Saudi Arabia",\n    gl: "sa",\n    hl: "ar-sa",\n  },\n  // Cairo and Casablanca follow the same shape.\n};`}</Code></Section>
    <Section title="2. The browser never receives the SerpApi key"><p>The client calls this application&apos;s own API route. The server reads <code>SERPAPI_KEY</code> only from the environment and sends the SerpApi request from the Node runtime.</p><Code>{`const apiKey = process.env.SERPAPI_KEY;\nif (!apiKey) {\n  throw new Error("Live search is not configured.");\n}\n\nconst response = await getJson({\n  engine: "google",\n  api_key: apiKey,\n  async: true,\n  q: query.ar,\n  location: market.location,\n  gl: market.gl,\n  hl: market.hl,\n  device: "desktop",\n});`}</Code></Section>
    <Section title="3. A real slow request changed the design"><p>A Baghdad test took roughly 33 seconds. Live mode therefore submits with <code>async=true</code>, returns the search ID, and lets the UI poll a first-party status endpoint rather than holding one long browser request open.</p><Code>{`const id = response.search_metadata?.id;\n\nconst archived = await getJsonBySearchId(id, {\n  api_key: process.env.SERPAPI_KEY!,\n});\n\nconst status = archived.search_metadata?.status;\n// Queued / Processing / Success / error`}</Code></Section>
    <Section title="4. Partial success is intentional"><p>Four regional searches should not behave like one all-or-nothing transaction. Submission and polling are handled per market, so completed results can render while another market is still processing or has failed.</p><Code>{`const settled = await Promise.allSettled(\n  selectedMarkets.map((marketId) =>\n    startMarketSearch(marketId, queryId)\n  )\n);\n\n// fulfilled markets become results/jobs;\n// rejected markets become market-specific errors.`}</Code></Section>
    <Section title="5. Public mode is quota-safe"><p>The production plan uses timestamped snapshots captured from real SerpApi responses. A snapshot is labeled as a snapshot; fabricated search data is never used. Live mode remains available server-side for controlled tests and demos.</p><Code>{`SERPAPI_LIVE_MODE=false\n\ndata/snapshots/<query-id>/<market-id>.json`}</Code></Section>
    <Section title="6. Scope is deliberately narrow"><p>No accounts, chatbot, social layer, arbitrary public free-text search or billing. The project exists to teach one thing clearly: Arabic-speaking markets are not one search context, and localization inputs should be explicit engineering decisions.</p></Section>
    <Section title="Build / quality gates"><ul><li>Next.js 16 + React 19 + TypeScript strict mode.</li><li>Production build and TypeScript checks pass on Render.</li><li>npm audit reported 0 vulnerabilities in the latest verified production build.</li><li>API key is never committed or rendered to the browser.</li><li>Truth boundary: independent demo, not an official SerpApi product.</li></ul></Section>
  </ProofArticle>
}
