import { Code, ProofArticle, Section } from "@/components/ProofArticle";

export default function SourcePage(){
  return <ProofArticle eyebrow="" title="How Arabic Search Context Lab is built" intro="These are the main implementation choices. The full source is public on GitHub.">
    <Section title="1. Each city has its own settings"><p>The query stays the same. Each city has a separate <code>location</code>, <code>gl</code>, and <code>hl</code> value.</p><Code>{`export const MARKETS = {\n  baghdad: {\n    location: "Baghdad,Baghdad Governorate,Iraq",\n    gl: "iq",\n    hl: "ar-iq",\n  },\n  riyadh: {\n    location: "Riyadh,Riyadh Province,Saudi Arabia",\n    gl: "sa",\n    hl: "ar-sa",\n  },\n  // Cairo and Casablanca use the same shape.\n};`}</Code></Section>
    <Section title="2. The API key stays on the server"><p>The browser calls this app's own API route. Only the server reads <code>SERPAPI_KEY</code> and sends the request to SerpApi.</p><Code>{`const apiKey = process.env.SERPAPI_KEY;\nif (!apiKey) {\n  throw new Error("Live search is not configured.");\n}\n\nconst response = await getJson({\n  engine: "google",\n  api_key: apiKey,\n  async: true,\n  q: query.ar,\n  location: market.location,\n  gl: market.gl,\n  hl: market.hl,\n  device: "desktop",\n});`}</Code></Section>
    <Section title="3. A 33-second Baghdad request changed the live flow"><p>One Baghdad test took about 33 seconds. Live mode now starts the search with <code>async=true</code>, keeps the search ID, and checks a server status route until the result is ready or the retry limit is reached.</p><Code>{`const id = response.search_metadata?.id;\n\nconst archived = await getJsonBySearchId(id, {\n  api_key: process.env.SERPAPI_KEY!,\n});\n\nconst status = archived.search_metadata?.status;\n// Queued / Processing / Success / error`}</Code></Section>
    <Section title="4. One slow city does not block the others"><p>Each city is submitted and checked separately. If Cairo finishes while Casablanca is still processing, Cairo can appear immediately.</p><Code>{`const settled = await Promise.allSettled(\n  selectedMarkets.map((marketId) =>\n    startMarketSearch(marketId, queryId)\n  )\n);\n\n// Each city keeps its own result or error.`}</Code></Section>
    <Section title="5. The public site reads saved results"><p>The live portfolio uses timestamped results captured from SerpApi. The site labels them as saved captures and does not invent search data. Live mode stays available on the server for controlled testing.</p><Code>{`SERPAPI_LIVE_MODE=false\n\ndata/snapshots/<query-id>/<market-id>.json`}</Code></Section>
    <Section title="6. The project stays small on purpose"><p>I left out accounts, billing, chat features, social features, and open-ended public search. The goal is to make one comparison easy to inspect.</p></Section>
    <Section title="Build checks"><ul><li>Next.js 16, React 19, and TypeScript.</li><li>Production build and TypeScript checks pass on Render.</li><li>The latest verified build reported 0 npm audit vulnerabilities.</li><li>The API key is not committed or sent to the browser.</li><li>This is my own project, not an official SerpApi product.</li></ul></Section>
  </ProofArticle>
}