import { Code, ProofArticle, Section } from "@/components/ProofArticle";

export default function SourcePage(){
  return <ProofArticle eyebrow="" title="How I built it" intro="The code is public. These are the decisions that mattered most while I was building the demo.">
    <Section title="1. I keep the market settings explicit"><p>Each city has its own <code>location</code>, <code>gl</code>, and <code>hl</code>. The query stays the same, so I can see what changes when the local search context changes.</p><Code>{`export const MARKETS = {\n  baghdad: {\n    location: "Baghdad,Baghdad Governorate,Iraq",\n    gl: "iq",\n    hl: "ar-iq",\n  },\n  riyadh: {\n    location: "Riyadh,Riyadh Province,Saudi Arabia",\n    gl: "sa",\n    hl: "ar-sa",\n  },\n  // Cairo and Casablanca use the same shape.\n};`}</Code></Section>
    <Section title="2. The API key stays on the server"><p>The browser calls my own Next.js route. That route reads <code>SERPAPI_KEY</code> from the server environment and sends the request to SerpApi. The key never needs to reach the browser.</p><Code>{`const apiKey = process.env.SERPAPI_KEY;\nif (!apiKey) {\n  throw new Error("Live search is not configured.");\n}\n\nconst response = await getJson({\n  engine: "google",\n  api_key: apiKey,\n  async: true,\n  q: query.ar,\n  location: market.location,\n  gl: market.gl,\n  hl: market.hl,\n  device: "desktop",\n});`}</Code></Section>
    <Section title="3. A slow search changed the live flow"><p>One Baghdad test took about 33 seconds. I changed live mode so it starts the search with <code>async=true</code>, keeps the search ID, and checks Search Archive until the result is ready.</p><Code>{`const id = response.search_metadata?.id;\n\nconst archived = await getJsonBySearchId(id, {\n  api_key: process.env.SERPAPI_KEY!,\n});\n\nconst status = archived.search_metadata?.status;\n// Queued / Processing / Success / error`}</Code></Section>
    <Section title="4. One slow city does not block the others"><p>I handle each market separately. If one search is still processing or fails, completed markets can still render.</p><Code>{`const settled = await Promise.allSettled(\n  selectedMarkets.map((marketId) =>\n    startMarketSearch(marketId, queryId)\n  )\n);`}</Code></Section>
    <Section title="5. The public site uses saved SerpApi results"><p>I did not want every portfolio visit to spend API quota. The public version uses timestamped results that I captured from SerpApi. Live mode is still in the code for controlled testing.</p><Code>{`SERPAPI_LIVE_MODE=false\n\ndata/snapshots/<query-id>/<market-id>.json`}</Code></Section>
    <Section title="6. I kept the project small"><p>No accounts, billing, chatbot, or general-purpose search box. The point of this project is the local search comparison, so I left out features that did not help explain it.</p></Section>
  </ProofArticle>
}
